### ISSUE TITLE
Not found rxjs operator

### ISSUE THREAD

**Issue by wolftrax5** [snowfrogdev/snowfrogdev#16]
Trying to use the lib, have the same error #15  , but after installing the dependency receive another one, related with "rxjs"
<img width="601" alt="Error in lib" src="https://user-images.githubusercontent.com/5388080/152201762-def714e6-74a9-4c15-8631-1a4914cab9f9.PNG">

related with the [rxjs Doc](https://rxjs.dev/api/operators/share) with the version 7 should be in operators

**Comment by snowfrogdev** [comment]
@wolftrax5 thanks for spotting that and for your PR. I have incorporated it in v1.0.3 which is now available on NPM. Let me know if that fixes the issue for you.
