### ISSUE TITLE
Can't bind to 'unleash' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by larsverp** [snowfrogdev/snowfrogdev#18]
I can't seem to get the unleash directives working. Followed the guide and I can see the network request being made. It results in 200 with all the correct data. However my console outputs `Can't bind to 'unleash' since it isn't a known property of 'div'.` on this line `<div class="page-section" *unleash="'dashboard.venue-designer'">`. Is there something I'm missing in the docs? :)

**Comment by snowfrogdev** [comment]
This kind of error is usually related to not importing the necessary Angular module in the right place. Have you imported the `NgxUnleashProxyClientModule` in your AppModule ? If so, could you see if the directive works when you apply it to an element in one of your top level components.

**Comment by larsverp** [comment]
Thanks! You were right, I imported the module in the wrong file.
