### ISSUE TITLE
Listen for 'impression' event

### ISSUE THREAD

**Issue by carlcrede** [snowfrogdev/snowfrogdev#19]
I was wondering if it's somehow possible to listen for the 'impression' event, so I can capture and track like it's shown in the docs:

```js
// listen for impression events
unleash.on("impression", (event) => {
    // capture and transform events
    posthog.capture(event.eventType, {
        ...event.context,
        distinct_id: event.context?.userId,
        featureName: event.featureName,
        enabled: event.enabled,
        variant: event.variant,
    });
});
```

**Comment by snowfrogdev** [comment]
Hi Christian, hopefully I'll get a chance to take a look at this in the
next few days. In the meantime, if you'd like, and are in a hurry, feel
free to submit a PR and I'll consider it.

**Comment by snowfrogdev** [comment]
Your wish is my command. New version is out.
https://www.npmjs.com/package/@snowfrog/ngx-unleash-proxy-client/v/2.0.0
https://github.com/snowfrogdev/snowfrogdev/commit/e1b4c32be27097c12100131b0965289a9d7ca15e
